language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet build -c Release
 - dotnet test lib12.Tests
 - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push lib12/bin/Release/lib12.*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
  on:
    branch: master